### ISSUE TITLE
Edge image support

### ISSUE THREAD

**Issue by VewDev** [LibrePass/LibrePass-Website#55]
Microsoft Edge does not support AVIF images yet, so the page doesn't load correctly on the browser.

![IMG20231214190054.jpg](https://github.com/LibrePass/LibrePass-Website/assets/115565209/27081445-4539-4f90-b125-b549b77ec036)

Sorry for posting a photo instead of a screenshot, it is not my computer and it was just easier.

Please consider using another image format until Edge support is added.

**Comment by OskarKarpinski** [comment]
Could you check if it works at https://test.librepass.medzik.dev?

**Comment by VewDev** [comment]
Its working perfectly now! Awesome!
